version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      expo:
        patterns:
          - expo
          - expo-*
          - '@expo/*'
          - react
          - react-dom
          - react-native
          - react-native-*
      development-tooling:
        dependency-type: development
        exclude-patterns:
          - expo
          - expo-*
          - '@expo/*'
          - react
          - react-dom
          - react-native
          - react-native-*

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
